// Code generated by '$ _run/creator_dependencies_Go.sh'. DO NOT EDIT.

package main

// // // // // // // // // // // // // // // // // //

var GlobalDependenciesMap = map[string]string{
	"github.com/Bookshelf-Writer/SimpleGenerator": "v0.6.1",
	"github.com/fatih/color":                      "v1.18.0",
	"github.com/ghodss/yaml":                      "v1.0.0",
	"github.com/pmezard/go-difflib":               "v1.0.0",
	"github.com/spf13/cobra":                      "v1.8.1",
	"golang.org/x/crypto":                         "v0.32.0",
	"github.com/inconshreveable/mousetrap":        "v1.1.0",
	"github.com/mattn/go-colorable":               "v0.1.14",
	"github.com/mattn/go-isatty":                  "v0.0.20",
	"github.com/niemeyer/pretty":                  "v0.0.0-20200227124842-a10e7caefd8e",
	"github.com/spf13/pflag":                      "v1.0.5",
	"golang.org/x/sys":                            "v0.29.0",
	"gopkg.in/check.v1":                           "v1.0.0-20200227125254-8fa46927fb4f",
	"gopkg.in/yaml.v2":                            "v2.4.0",
}
