// Code generated by '$ _run/creator_const_Go.sh'. DO NOT EDIT.

package main

// // // // // // // // // // // // // // // // // //

const (
	GlobalName       string = "treelang"
	GlobalDateUpdate string = "06-21-2025"
	GlobalHash       string = "ee01e8c916f1ea2110e3ff34b98449c4e09b7ac8"

	GlobalVersion      string = "2.5.2"
	GlobalVersionMajor string = "2"
	GlobalVersionMinor uint16 = 5
	GlobalVersionPatch uint16 = 2
)
