// Code generated by '$ _run/creator_const_Go.sh'. DO NOT EDIT.

package main

// // // // // // // // // // // // // // // // // //

const (
	GlobalName       string = "treelang"
	GlobalDateUpdate string = "06-21-2025"
	GlobalHash       string = "6843ecaf8e619b2573b1bed186b13027851ebfaf"

	GlobalVersion      string = "2.5.1"
	GlobalVersionMajor string = "2"
	GlobalVersionMinor uint16 = 5
	GlobalVersionPatch uint16 = 1
)
