#!/bin/bash
# Original source: https://github.com/Bookshelf-Writer/scripts-for-integration/blob/main/_run/creator_dependencies_Go.sh

dir_path=""
file_name="value_dependencies.go"
package_name="main"

#############################################################################
#############################################################################

run_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_path=$(cd "$run_dir/.." && pwd)

file_go_mod="$root_path/go.mod"
file_const="$root_path/$dir_path$file_name"

if [[ ! -f "$file_go_mod" ]]; then
    exit 1
fi

#############################################################################
          ################[ File generation ]################

{
    echo -e "// Code generated by '$ _run/creator_dependencies_Go.sh'. DO NOT EDIT."
    echo ""
    echo "package $package_name"
    echo ""
    echo "// // // // // // // // // // // // // // // // // //"
    echo ""
    echo "var GlobalDependenciesMap = map[string]string{"

    while IFS= read -r line; do
        if [[ "$line" =~ ^\	 ]]; then
            dep=$(echo "$line" | awk '{print $1}')
            ver=$(echo "$line" | awk '{print $2}')

            echo "    \"$dep\": \"$ver\","
        fi
    done < "$file_go_mod"

    echo "}"
} > "$file_const"

exit 0
