name: Go Tests and Benchmarks

on:
  pull_request:
    paths-ignore:
      - '*.txt'
      - '*.md'
      - '*.pdf'
  push:
    tags-ignore:
      - '*'

jobs:
  generate:
    name: "Generate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run go generate
        run: go generate

      - name: Upload updated repository as artifact
        uses: actions/upload-artifact@v3
        with:
          name: updated-repo
          path: .

  test:
    name: "Test and Benchmark [${{ matrix.os }}]"
    needs: generate
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.22]
    permissions:
      contents: write
    steps:
      - name: Download updated repository
        uses: actions/download-artifact@v3
        with:
          name: updated-repo
          path: .

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.os == 'Windows' && format('{0}\\go\\pkg\\mod', env.USERPROFILE) || '~/go/pkg/mod' }}
            ${{ runner.os == 'Windows' && format('{0}\\go\\bin', env.USERPROFILE) || '~/go/bin' }}
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./... || exit 1

      - name: Run benchmarks
        run: go test -bench . -v ./... || exit 1