name: Go Tests and Benchmarks

on:
  pull_request:
    paths-ignore:
      - '*.txt'
      - '*.md'
      - '*.pdf'
  push:
    tags-ignore:
      - '*'

jobs:
  generate:
    name: "Generate Files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies and generate files
        run: |
          go generate
          go mod tidy

      - name: Upload generated files
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: |
            .
          retention-days: 1

  test:
    name: "Test and Benchmark [${{ matrix.os }} - Go ${{ matrix.go-version }}]"
    needs: generate
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download generated files
        uses: actions/download-artifact@v3
        with:
          name: generated-files
          path: .

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: |
          echo "Running tests..."
          go test -v ./... || exit 1

      - name: Run benchmarks
        run: |
          echo "Running benchmarks..."
          go test -bench . -v ./... || exit 1
